* 股票基础知识
** 股票交易所与交易规则
证券交易所:
中国:
上海证券交易所(上交所), 股票代码以60开头
深圳证券交易所(深交所), 以00, 002, 300开头
香港交易所(港交所)

美国:
纽约证券交易所(纽交所)
纳斯达克证券交易所(纳斯达克)

交易时间:
|      | 交易时间(北京时间星期一至星期五正常工作日) | 最小交易单位 | 涨跌幅                  |
| A股  | 正常交易时间段: 09:30-11:30, 13:00-15:00   | 1手(100股)   | 前一交易日收盘价的+-10% |
|      | 集合竞价时间: 09:15-09:25, 14:57:15:00     |              |                         |
|------+--------------------------------------------+--------------+-------------------------|
| 港股 | 正常交易时间段: 9:30-12:00, 13:00-16:00    | 1手          | 没有单日涨跌幅限制      |
|      | 早盘集合竞价时间段 09:00-09:20             |              |                         |
|------+--------------------------------------------+--------------+-------------------------|
| 美股 | 夏令时:                                    | 1股          | 没有单日涨跌幅限制      |
|      | 盘前: 16:00-21:30, 盘中 21:30-04:00,       |              |                         |
|      | 盘后: 04:00-08:00                          |              |                         |
|      | 冬令时:                                    |              |                         |
|      | 盘前: 17:00-22:30, 盘中: 22:30-05:00,      |              |                         |
|      | 盘后: 05:00-09:00                          |              |                         |
港股每手所含的股票数量根据股票价格来决定, 1手可能是100股、500股、1000股、2000股不等.

交易规则:
1. 价格优先
   较高价格的买进申报优于较低价格买进申报, 较低价格的卖出申报优于较高价格卖出申报
2. 时间优先
   买卖方向、价格相同的, 先申报优于后申报, 先后顺序按交易主机接受申报的时间确定
3. 集合竞价时成交价格的确定原则
   1. 在有效价格范围内选取成交量最大的价位
   2. 高于成交价格的买进申报与低于成交价格的卖出申报全部成交
   3. 与成交价格相同的买方或卖方至少一方全部成交
   
** 概念
股票: 股票是一种有价证券, 是股份有限公司在筹集资本时向出资人发行的股份凭证, 代表着其持有者(股东)对
股份公司的所有权. 股东能通过股票转让收回其投资, 但不能要求公司返还其出资.

IPO: Initial Public Offering, 首次公开募股是指一家企业或公司第一次将它的股份向公众出售(
首次公开发行, 指股份公司首次向社会公众公开招股的发行方式).

打新股: 用资金参与新股申购, 如果中签的话, 就买到了即将上市的股票.

** 股票分类
根据收益分配以及管理权限等分为:
普通股: 是随企业利润变动而变动的一种股份, 是公司资本构成中最普通、最基本的股份、是股份企业资金的
基础部分. 目前上海和深圳上市的股票均为普通股.

优先股: 是股份公司发行的, 在分配红利和剩余财产时比普通股具有优先权的股份, 优先股通常预先确定
股息收益率, 其权利范围小.

依据上市地点及面对投资者分为:
A股: 人民币普通股票, 是由我国境内的公司发行, 供境内机构、组织和个人(不含港澳台投资者)以人民币认购
和交易的普通股票

B股: 人民币特种股票, 以人民币标明面值, 以外币认购和买卖, 在境内证券交易所上市交易的股票. B股公司的
注册和上市地都在境内, 只不过投资者在境外或者港澳台.

H股: 在境内注册的, 在香港发行并在香港联合交易所上市的普通股票.

** 股票类别名称
大盘股: 股本比较大的股票, 总股本都在几十亿股以上. 市场疲软时, 小盘股机会较多. 由于流通盘大, 对
指数的影响大, 往往成为市场调控指数的工具.

白马股: 业绩较为明朗, 同时兼有业绩优良、高成长、低风险的特点, 具备较高的投资价值.
成长股: 销售额和利润额持续增长, 且速度快于整个国家和本行业的增长的公司发行的股票.
龙头股: 在某一时期在股票市场的炒作中对同行业板块的其他股票具有影响力和号召力的股票, 具有"先于大盘
企稳、先于大盘启动、先于大盘放量"的特征
ST股: Special Treatment, 是财务出现状况或其他异常状况的上市公司, 日涨跌幅限制为5%.

ST不是对上市公司的处罚, 而只是对上市公司目前所处状况的一种客观提示, 如果公司异常状况清除, 取消ST
冠名, 称之为"摘帽".

** 股价指数概念与计算方式
股价指数: 也叫指数, 是动态地反映某个时期股市总价格水平的一种相对指标.

算术平均法,
加权平均法, 股票在股市的影响力一般是以股票发行总数或成交量作为标准的, 称为权数.

** 常用的股价指数
A股:
上证指数(000001): 上海证券交易所编制的股票指数, 指数样本为所有在上海证券交易所挂牌上市的股票.
上证指数是以各上市公司的总股本为加权计算出来的, 故盘子大的股票较能左右上证指数的走势.

沪深300指数(000300): 从上交所和深交所挑选出规模最大、流动性最好的300只股票, 所包括的公司从市值
规模占到国内股市全部规模的60%以上, 被认为是国内股市最具代表性的指数.

深证指数(399001): 由深圳证券交易所编制的股价指数, 其样本为所有在深圳证券交易所挂牌上市的股票,
权数是股票的总股本.

创业板指数(399006): 按照创业板所有股票的流通市值, 一个个计算当天的股价, 再加权平均所得.

中证指数(000905): 国内中型公司的代表, 排除深沪300的公司, 在剩下的公司中选择近一年日均总市值排名
前500名的企业股票构成的.

港股美股常用指数:
恒生指数(HSI): 由香港恒生银行全资附属的恒生指数公司编制的指数. 入选样板股为香港股票市场33家上市
公司, 是以发行量为权数的加权平均股价指数. 为香港股票市场最有影响的指数.

道琼斯指数(DJIA): 全称为股票平均价格指数

纳斯达克指数(NDX): 基本指数是100.
标普500指数(SPX): 美国影响力最大的一个股票指数, 不单纯按照规模, 但入选的都是一个行业排在前列
的领导者.

