* 心理学
** 基础
1. 心理系统就像一个鱼缸, 自己就是鱼缸里的那条鱼, 你在里边游起来很自由, 其实你是被限制住了.
2. 防御性思维
3. 成长型思维
4. 改变的前提是理解自己, 而理解自己就需要有内省的能力
5. 内省才是我们自我发展真正的动力.
6. 改变是一种选择, 不改变也是一种选择
7. 为自己不改变找的借口统统都是你的选择, 甚至连告诉自己"我没有选择"也是你的选择.
8. 选择是基于当前的现实, 而不是头脑中的理想. 我们选择的不是未来的结果而是此时此地的行动
9. 总觉得没有选择的原因
   a. 误认为只有你的选项足够理想, 这才是选择; 如果选择不够好, 就是没有选择
   b. 逃避对自己的责任
10. 讨论对错的思维方式, 通常会假象一个施害者和受害者
    当说没有选择的时候, 是将自己放到了受害者的位置, 可以借此将责任推卸给假象中的施害者.
    这样就不会有心理负担了.

    换一种思维方式, 不是思考"谁对谁错", 而是要思考"有用没用".
11. 躯体里有两个自我, 一个是感性的自我, 一个是理性的自我
    乔纳森.海特用一个有趣的比喻来描述两个自我之间的关系.
    人的情感面就像一头大象, 理智面就像一个骑象的人. 骑象人骑在大象背上, 手里握着缰绳, 好像是他
    在指挥大象, 但事实上, 他的力量微不住道, 一旦和大象发生冲突, 那他通常是拗不过大象的.

    大象的特点: 1. 力量大 2. 它是受情感激发的 3. 它是受经验支配的

12. 对于改变, 理智提供方向, 情感提供动力
13. 期待的好处就是想象中的好处
    期待的好处是抽象的, 经验的好处是具体的
    期待的好处发生在未来, 经验的好处发生在过去或者现在
    期待的好处是被教导出来的, 经验的好处是通过亲身体会, 真实感受到的
14. 强化, 就是经验的好处
    一旦某个行为获得了这种好处, 就会被保留到我们的生命里, 哪怕我们没有意识到, 它任然会影响我们的
    行为
15. 正强化是当表现某种行为时, 通过增加想要的结果让行为更巩固
16. 负强化是当表现某种行为时, 通过减少你想要的结果让行为更为巩固
17. 当改变失败的时候, 责怪自己时没有用的, 因为我们的行为并不是独立于环境而存在的
    所谓的好处和坏处其实就是我们与环境交换信息获得反馈的过程.
18. 改变的本质: 创造新经验, 用新经验代替就经验的过程

** 心理舒适区
心理舒适区本质: 熟悉的应对方式.
1. 心理舒适区并不一定意味着舒适.
   如电影《肖申克的救渎》中老布的处境. 监狱环境虽然不舒服, 但这是他的心理舒适区
2. 心理舒适区也并不意味着熟悉的环境.
3. 走出心理舒适区, 说的就是改变我们应对的方式.
4. 心理学上有一个常用的量表, 叫应对方式量表, 归纳了六种常用的应对方式.
   解决问题 -> 自责 -> 求助 -> 幻想 -> 退避 -> 合理化
   应对方式有两种含义: a. 行为上的应对即对具体事情的应对.
   b. 对内心的情绪应对
5. 心理舒适区的好处是带来了控制感, 控制感是人安全感的来源.
6. 心理舒适区最特别的地方在于我们会用自己的应对方式去构建生活,
   而不是根据生活选择一种合适的应对方式
7. 觉得自己配不上好的东西, 这也是另一种心理舒适区
8. 越是感到自己受到了威胁, 越是感到焦虑, 我们就越需要控制感, 抓着已有的应对方式不放,
   这就是为什么改变那么难
9. 需要面对自己内心真实的爱和怕, 需要改变自己的思维方式, 走出自己的心理舒适区, 才能获得新的经验
10. 心理免疫的X光片 - 罗伯特.凯根
    他认为, 就像人有一套生理免疫系统来排斥不属于身体的微生物一样, 人的心理也有一套免疫系统,
    会排斥我们采取新的行为方式, 以此来维持心理结构的平衡和稳定.

    心理免疫系统的本质是一套焦虑控制系统.

    心理免疫系统X光片是一张四栏表:
    第一栏: 希望达成的行为目标. 心理免疫系统的目标是用行为来标识的.
    第二栏: 正在做的哪些跟目标相反的行为
    第三栏: 这些与目标相反的行为, 有哪些隐含的好处. 如果还不清楚好处, 可以问自己, 如果不这么做
    所担心的最糟糕的事情是什么
    第四栏: 让这些好处成立的重大假设

    一个金典的比喻: 我们想要车运行, 却一只脚踩着油门, 另一只脚踩着刹车. 而能量和动力, 就在这样的
    空转声中痛苦的消耗着.
11. 如果潜意识的东西不能转换成意识, 就会变成我们的命运指引我们的人生.

** 改变的四个原则
1. 第一个原则: 重要假设的检验
   改变第一步: 看见内心假设, 可以提三个问题
   a. 那些跟你的目标相反的行为, 带给你的好处是什么?
   b. 如果你做不一样的行为, 你最担心比人会怎么对你?
   c. 为什么阻碍改变的行为, 所带来的好处是必须的, 如果没有这些好处, 会发生什么可怕的事情?

   在寻找自己的重要假设时, 可以试着用"如果...就..."的句型.

   行为检验: 验证内心假设
   当新行为带来内心假设的松动后, 所产生的新的领悟. 这个领悟会被整合到我们的心理免疫系统中,
   最终改变我们的心理免疫系统, 此时改变就发生了.

   如果要进一步改变, 还需要像一个行为科学家一样, 有针对性地设计一些新行为, 来测试这些基本假设.

   改变是一种有支持的探索, 即需要勇敢也需要安全和可控.

   新的经验常常是在预期经验和真实经验之间的对照中产生的.

   如果你觉得重要的东西, 就要去争取, 而不是背后抱怨
2. 第二个原则: 小步子原理
   "小步子原理"简单来说, 就是在改变的路上迈出小小的一步, 获得一个小小的成功, 让每一次的小成功
   成为下一次改变的基础.

* 语句
陀思妥耶夫斯基说过: 有些话你只能讲给朋友听, 有些话连朋友也不能讲, 还有一些话你甚至都不敢将
给自己听.

* 书籍
斯科特.派克(Scott Peck):  《少有人走的路》
